name: Arcly
options:
  bundleIdPrefix: com.qingshan
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "26.4"

settings:
  base:
    SWIFT_VERSION: "5"
    MACOSX_DEPLOYMENT_TARGET: "26.0"
    PRODUCT_NAME: Arcly
    MARKETING_VERSION: "1.0.1"
    CURRENT_PROJECT_VERSION: "3"

targets:
  Arcly:
    type: application
    platform: macOS
    sources:
      - path: Sources/Arcly
        type: group
      - path: Resources/Assets.xcassets
      - path: Resources/en.lproj/Localizable.strings
      - path: Resources/zh-Hans.lproj/Localizable.strings
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.qingshan.orbis
        INFOPLIST_FILE: ""
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: Arcly
        INFOPLIST_KEY_LSUIElement: true
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
        INFOPLIST_KEY_CFBundleIconName: AppIcon
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2025 Arcly. All rights reserved."
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: false
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 9NDTK4FT92
        ENABLE_HARDENED_RUNTIME: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: true
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: Arcly.debug.entitlements
        Release:
          CODE_SIGN_ENTITLEMENTS: Arcly.entitlements
